 # fos_user:
 #    resource: "@FOSUserBundle/Resources/config/routing/all.xml"  #AJOUT
  # app_logout:    #AJOUT
  #    path: /logout  #AJOUT
  #    methods: GET  #AJOUT
 # index:
 #    path: /
 #    controller: App\Controller\DefaultController::index
